In [1]:
import numpy as np
import glob
from functools import reduce
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_calendar = pd.read_csv('../m5-dataset/calendar.csv')
df_calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [3]:
event_names_1 = df_calendar['event_name_1'].dropna().drop_duplicates().tolist()
event_names_2 = df_calendar['event_name_2'].dropna().drop_duplicates().tolist()
event_types_1 = df_calendar['event_type_1'].dropna().drop_duplicates().tolist()
event_types_2 = df_calendar['event_type_2'].dropna().drop_duplicates().tolist()

print(event_names_1)
print(event_names_2)
print(event_types_1)
print(event_types_2)

['SuperBowl', 'ValentinesDay', 'PresidentsDay', 'LentStart', 'LentWeek2', 'StPatricksDay', 'Purim End', 'OrthodoxEaster', 'Pesach End', 'Cinco De Mayo', "Mother's day", 'MemorialDay', 'NBAFinalsStart', 'NBAFinalsEnd', "Father's day", 'IndependenceDay', 'Ramadan starts', 'Eid al-Fitr', 'LaborDay', 'ColumbusDay', 'Halloween', 'EidAlAdha', 'VeteransDay', 'Thanksgiving', 'Christmas', 'Chanukah End', 'NewYear', 'OrthodoxChristmas', 'MartinLutherKingDay', 'Easter']
['Easter', 'Cinco De Mayo', 'OrthodoxEaster', "Father's day"]
['Sporting', 'Cultural', 'National', 'Religious']
['Cultural', 'Religious']

In [5]:
df_final = pd.read_parquet('../Data/final_dataset_wo_date_state.pqt')
df_final.head()

,item_id,store_id,units_sold,event_name_1,event_type_1,event_name_2,event_type_2,sell_price,day_of_week,day_of_month,month,year,state_cpi,state_ur,state_gas_price,consumer_sentiment,state_snap
0,1437,0,0,30,4,4,2,0.459961,5,29,1,2011,237.125,12.101562,3.292969,74.1875,0
1,428,6,0,30,4,4,2,1.879883,5,29,1,2011,200.250,8.203125,2.974609,74.1875,0
2,427,6,0,30,4,4,2,1.879883,5,29,1,2011,200.250,8.203125,2.974609,74.1875,0
3,426,6,5,30,4,4,2,3.779297,5,29,1,2011,200.250,8.203125,2.974609,74.1875,0
4,425,6,1,30,4,4,2,2.419922,5,29,1,2011,200.250,8.203125,2.974609,74.1875,0