In [45]:
import sys
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from tqdm import tqdm
import sklearn.preprocessing
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import tabulate as tabulate
import json
import math

In [ ]:
lstm_path = '../models/LSTM_10epochs_final.pth'
trans_path = '../models/Transformer_13epochs_final.pth'

lstm_model = torch.load(lstm_path, map_location='cpu')
trans_model = torch.load(trans_path, map_location='cpu')

df_lstm_history = pd.DataFrame(lstm_model['history'])
df_trans_history = pd.DataFrame(trans_model['history'])

pd.set_option('display.float_format', '{:.8f}'.format)

C:\Users\juliub\AppData\Local\Temp\ipykernel_33328\3152202091.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  lstm_model = torch.load(lstm_path, map_location='cpu')
C:\Users\juliub\AppData\Local\Temp\ipykernel_33328\3152202091.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  trans_model = torch.load(trans_path, map_location='cpu')

In [47]:
df_lstm_history['epoch_time'] = df_lstm_history['epoch_time'].round(2)
df_lstm_history.head(10)

   train_loss   val_loss  epoch   epoch_time
0  0.00001755 0.00000895      0 143.31000000
1  0.00001050 0.00000989      1 141.59000000
2  0.00001032 0.00000897      2 145.15000000
3  0.00001020 0.00000890      3 143.23000000
4  0.00001013 0.00001042      4 143.48000000
5  0.00000998 0.00000939      5 142.36000000
6  0.00000982 0.00000964      6 144.42000000
7  0.00000971 0.00000959      7 145.17000000
8  0.00000970 0.00000969      8 144.59000000
9  0.00000969 0.00000967      9 145.97000000

In [ ]:
df_trans_history['epoch_time'] = df_trans_history['epoch_time'].round(2)
df_trans_history.head(20)

    train_loss   val_loss  epoch   epoch_time
0   0.00322930 0.00002180      0 337.10000000
1   0.00003734 0.00002080      1 333.64000000
2   0.00003000 0.00002079      2 332.53000000
3   0.00002817 0.00002075      3 331.95000000
4   0.00002711 0.00002084      4 330.95000000
5   0.00002647 0.00002062      5 332.26000000
6   0.00002609 0.00002027      6 332.43000000
7   0.00002140 0.00001181      7 331.90000000
8   0.00001441 0.00001037      8 330.35000000
9   0.00001423 0.00000937     10 337.77000000
10  0.00001215 0.00000940     11 331.32000000
11  0.00001168 0.00000916     12 332.24000000
12  0.00001164 0.00000920     13 333.28000000
13  0.00001100 0.00000953     14 330.83000000
14  0.00001088 0.00000979     15 331.14000000
15  0.00001036 0.00000980     16 332.76000000
16  0.00001032 0.00000978     17 331.80000000
17  0.00001025 0.00000994     18 330.38000000
18  0.00001013 0.00000987     19 333.01000000